config/routes.rb
Rails.application.routes.draw do
 

#localhost3000 to get github

  
 resources :users, only: [:new, :create, :show, :edit]
 get 'users/new', to: 'users#new'
   get '/signin', to: 'sessions#new'
    get '/auth/:provider/callback' => 'sessions#create'
  post "/signin", to: "sessions#create"
 get "/signout", to: "sessions#destroy" 
 
 root 'welcome#home'
 

 resources :houses do
    resources :guests, only: [ :new, :create, :show,  :index, :destroy ]

end

resources :guests
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/guest.rb
class  Guest < ApplicationRecord
    
     belongs_to :user
     belongs_to :house


     
     validates :name, presence: true
     validates :email, presence: true, uniqueness: true
     validates :phone_number, presence: true, uniqueness: true

#homework scope
     scope :test, -> { where(comment: 'test') } do

          
         
end
end

app/models/house.rb
class  House < ApplicationRecord
    has_many :guests, dependent: :destroy 
    has_many :users, through: :guests
    accepts_nested_attributes_for :guests

    validates :address, uniqueness: true, presence: true,
    length: { minimum: 5 }


end

app/models/user.rb
class  User < ApplicationRecord

    
    has_many :guests  
    has_many :houses,   through: :guests
    has_secure_password
    
    
    #  validates :name, uniqueness: true
    #  validates :name, presence: true
    #  validates :email, presence: true
    #  validates :email, uniqueness: true
    #  validates :password_digest, uniqueness: true
    #  validates :password_digest, presence: true



def self.find_or_create_by_omniauth(auth_hash)
    self.where(:email=> auth_hash["info"]["email"]).first_or_create do |user|
        # raise.error
        user.name = ( auth_hash["info"]["nickname"])
        # user.email =  ( auth_hash["info"]["GitHub"])
       user.password = SecureRandom.hex
    end
 end
end
     

    #  def self.sign_in_from_omniauth(auth)
    #     find_by(provider: auth['provider'],) uid: auth['uid']) || create_user_from_omniauth(auth)
    # end
    
    
    
    # def self.create_user_from_omniauth(auth)
    #     create(
    #         provider: auth['provider'],
    #         uid: auth['uid'],
    #         name: auth['info']['name']
    
    #     )
    #  end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
    helper_method :current_user

def logged_in?
  !!current_user
end


def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
    before_action :require_login
    # http_basic_authenticate_with name: "@user.name", password: "@user.password", only: :index



      def index
          @guests = Guest.all
      end 

      


      def new
          @guest = Guest.new
      end

    
      def create
        @guest = current_user.guests.build(guest_params)
        @house = @guest.house_id
        if @guest.save
        redirect_to house_path(@house)
      else
        render 'new'
        end
      end



    #  @project = @current_user.projects.find(params[:id])
        def show
         @guest = Guest.find_by(id: params[:id])  
      end


    # Post.where("author_id = ?", @author.id)
    def edit 
        @guest = Guest.find_by(id: params[:id])
    end 

    

    def update
        @guest = Guest.find_by(id: params[:id])
        @guest.update(guest_params)
         redirect_to house_path(@guest)
        
      end



      

    def destroy
         @house = House.find(params[:house_id])
        @guest = @house.guests.find(params[:id])
        @guest.destroy
        redirect_to house_path(@house)
      end


  


    private 

    
    def guest_params
        params.require(:guest).permit(:name, :phone_number, :address, :email, :time_line, :comment, :user_id,:house_id)
    end 


    def require_login
      # return head(:forbidden) unless session.include? :user_id
          return head(:forbidden) unless logged_in?
      end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

      # http_basic_authenticate_with name: "@user.name", password: "@user.password", only: :show

      before_action :require_login
    


      def index
          @houses = House.all
      end

      
        def show  
          @house = House.find_by(id: params[:id])
        end
      
      
        
        def new
          @house = House.new
        end

        def edit
          @house = House.find_by(id: params[:id])
        
        end


        
        def create
  #      render plain: params[:article].inspect
  #    end
          @house = House.new(house_params)
          if @house.save
          redirect_to @house
          else
            render 'new'
        end
      end
      

        def update
          @house = House.find_by(id: params[:id])
        if  @house.update(house_params)
          redirect_to @house
        else
          render 'edit'
        end 
      end
        
        

  #destroy will destroy  the house and all guests associate with it to avoid bad data to persist.
        def destroy
          @house = House.find( params[:id])
          @house.destroy
          redirect_to houses_path
        end
      
        private
          def house_params
            params.require(:house).permit( :address, :comment)
          end


          def require_login
            # return head(:forbidden) unless session.include? :user_id
            return head(:forbidden) unless logged_in?
          end
      end






    

app/controllers/sessions_controller.rb
require 'pry'

class SessionsController < ApplicationController
  

  def new 
  end


  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render 'new'
      end
    end
  end

  

  def destroy
      reset_session
      redirect_to root_path
      end 
    end


  # def create 
  #   raise "STOP".inspect
  # request.env , request.class, request.env["omniauth.auth"]
  #   @user = User.find_by(email: params[:email])
  #  if @user && @user.authenticate(params[:password])
  #   session[:user_id] = @user.id
  #    redirect_to user_path(@user)
  #  else 
  #     render 'new'
    
  # end
# end

  

    # def destroy
    #   session.destroy
    #   redirect_to root_path
    #   end 
    # end


# def create
#   @user = User.find_or_create_from_auth_hash(auth_hash)
#   self.current_user = @user
#   redirect_to '/'
# end

# protected

# def auth_hash
#   request.env['omniauth.auth']
# end
# end
   
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    


    def new
        @user = User.new
    end 


     def create
       
        @user = User.new(user_params)
        if @user.save
         session[:user_id] = @user.id
        
         redirect_to user_path(@user), :alert=> "Welcome to Open house app! You Signed up / Bienvenue"
        else 
            render 'new', :alert=> "Please fill in the form"
      end 
    end



def edit
    @user = User.find_by(id: params[:id])
end


    def show 
        return redirect_to root_path unless logged_in?
        @user = User.find_by(id: params[:id])
    end 


    private 

   
    def user_params
        params.require(:user).permit(:name, :email, :password)
     end 
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   
def home
  #   if session[:user_id]
  #     @user = User.find(session[:user_id])
  #   end
   end


#    def set_auth
#     @auth = session[:omniauth] if session [aumniauth]
# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/_form.html.erb
<%= form_for @guest do |f| %>

  <% if @guest.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@guest.errors.count, "error") %> prohibited
      this guest from being saved:
    </h2>
    <p>
      <% @guest.errors.full_messages.each do |msg| %>
        <h3><%= msg %></h3>
      <% end %>
    </p>
  </div>
  <% end %>
  

  <br><label> Name:</label><br>
  <%= f.text_field :name %></br>

  <label>Phone number:</label><br>
  <%= f.telephone_field :phone_number %></br>
  
  <label>address:</label><br>
  <%= f.text_field :address %></br>
  
  <label>email:</label><br>
  <%= f.email_field :email %></br>
  
  <label>time line:</label><br>
  <%= f.text_field :time_line %></br>
  
  <label>comment:</label><br>
  <%= f.text_field :comment %></br>

  <%= f.hidden_field :user_id %>

  <%= f.hidden_field :user_id %>

  <%= f.collection_select( :house_id, House.all, :id, :address, :prompt=>true) %>
 
  
 
  <%= f.submit %>

<% end %>
   
    
    
    
  

app/views/guests/edit.html.erb
<style>
img {
opacity: 0.5;
}
</style>
<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
<div class="centered">
<h2>Edit Guest</h2>
<%= render partial: 'form'%>
</div>
</div>

app/views/guests/index.html.erb
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  
  border: 1px solid #ddd;
  padding: 8px;
}

# customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: center;
  background-color: #4CAF50;
  color: white;
}
</style>
<button>
<a  <%= link_to 'Back', houses_path %></a>
</button>

        </head>
        <body>
        <table id="customers" %>
        <tr>
        <th>ID:</th>
        <th>Name:</th>
        <th>Phone:</th>
        <th>Address:</th>
        <th>Email:</th>
        <th>Timeline:</th>
        <th>Note:</th>
        </tr>
        

    <% if @guests = current_user.guests %>
    <% @guests.each  do | guest|%>
        
        <tr>
        <td><%= guest.id %></td>
        <td><%= guest.name %></td>
        <td><%= guest.phone_number %></td>
        <td><%= guest.address %></td>
        <td><%= guest.email %></td>
        <td><%= guest.time_line %></td>
        <td><%= guest.comment %></td>
        

        
       

<% end %>


<%else%>

<h1><%= no guests to show %><h1>

<% end %>

app/views/guests/new.html.erb
<style>
img {
opacity: 0.5;
}
</style>
<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
<div class="centered">
<%= render partial: 'form'%>
</di>
</div>


  

app/views/guests/show.html.erb
<style>
img {
opacity: 0.5;
}
</style>
<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
<div class="centered">
 <h1> GUEST/SHOW </h1>
 <%= form_for @guest do |f| %>

 <label> Name:</label><br>
<%= f.text_field :name %></br>

<label>Phone number:</label><br>
<%= f.telephone_field :phone_number %></br>

<label>address:</label><br>
<%= f.text_field :address %></br>

<label>email:</label><br>
<%= f.email_field :email %></br>

<label>time line:</label><br>
<%= f.text_field :time_line %></br>

<label>comment:</label><br>
<%= f.text_field :comment %></br>

<%= f.hidden_field :user_id %>

<%= f.hidden_field :house_id %>


<%= f.collection_select( :house_id, House.all, :id, :address, :prompt=>true) %>
 
  
 

</div>
</div>

<% end %>



<%= link_to 'Edit Guest', edit_guest_path(@guest) %>


  
  

 

app/views/houses/_form.html.erb
<%= form_for @house do |f| %>

  <% if @house.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@house.errors.count, "error") %> prohibited
      this house from being saved:
    </h2>
    <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

    
    <p>
    <label> address:</label><br>
    <%= f.text_field :address %><br>
    </p>
    
    <p>
    <label>comment:</label><br>
    <%= f.text_field :comment %><br>
    </p>

    <p>
    <%= f.submit %>
    <p>
  <% end %>

app/views/houses/edit.html.erb
       <style>  
        img {
        opacity: 0.5;
        }
        </style>
        <body>
        <div class="container">
        <%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
        </body>
        <div class="centered">
        <h2>Edit House</h2>
        <%= render partial: 'form'%>
       <button>
        <%= link_to 'Back', houses_path %>
        </button>
        </div>
        </div> 

app/views/houses/index.html.erb
<style>
img {
  opacity: 0.5;
}
</style>



<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
<div class="centered">
<h1> Your Houses List</h1>
<% if @houses = current_user.houses %>


    <% @houses.each do |house| %>

<br></br>      
 <button>
 <%= link_to "Show #{house.address}", house_path(house) %>
 </button>

 <% end %>

 <br></br>
 <button>
 <p><%= link_to "New House", new_house_path  %></p>
 </button>


<% else %>

<br></br>
<button>
<p><%= link_to "New House", new_house_path  %></p>
</button>
</div>
<% end %>

app/views/houses/new.html.erb
       <style>
        img {
        opacity: 0.5;
        }
        </style>
        <body>
        <div class="container">
        <%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
        </body>
        <div class="centered">
        <h1>New House</h1>
        <%= render partial: 'form'%>
       <button>
        <%= link_to 'Back', houses_path %>
        </button>
        </div>
        </div> 
        

app/views/houses/show.html.erb
<style>
        img {
        opacity: 0.5;
        }
        /* Needed to position the navbar */
  position: relative;
}

/* Position the navbar container inside the image */
.container {
  position: absolute;
  margin: 20px;
  width: auto;
}

/* The navbar */
.topnav {
  overflow: hidden;
  background-color: #333;
}

/* Navbar links */
.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}
 </style>
        
                <div class="bg-img">
                <div class="container">
                <div class="topnav">
                <a  <%= link_to 'Edit House', edit_house_path(@house) %></a>
                <a  <%= link_to 'Back', houses_path %></a>
                <a  <%= link_to "Delete", @house, method: :delete, data: {confirm: "Really?"} %></a>
                <a  <%= link_to 'Index Guests ', guests_path %> </a>
                <a <%= link_to 'Sign Out', signout_path %></a>
                </div>
                </div>
                </div>

                <body>
                <div class="container">
                <%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
                </body>

                <div class="centered">
                <h1> House infos </h1>
                <p>
                <strong>Address:</strong>
                <%= @house.address %>
                </p>
                <p>
                <strong>Comment:</strong>
                <%= @house.comment %>
                </p>

                <h2>Guests: <%= @house.guests.count %></h2>
                <% @house.guests.each do |guest| %>
                <p>
                <p>
                <li>
                <label>Name:</label> <%= guest.name %>
                </li>
                <%end%> 

                <h2> Create guests:</h2>
                <%= form_with model: [ @house, @house.guests.build ], local: true do |form| %>
                <p>
                <%= form.label :name %><br>
                <%= form.text_field :name %>
                </p>
                <p>
                <%= form.label :phone_number %><br>
                <%= form.text_field :phone_number%>
                </p>
                <p>
                <%= form.label :address  %><br>
                <%= form.text_field :address %>
                </p>
                <p>
                <%= form.label :email  %><br>
                <%= form.text_field :email %>
                </p>
                <p>
                <%= form.label :time_line  %><br>
                <%= form.text_field :time_line %>
                </p>
                <p>
                <%= form.label :comment  %><br>
                <%= form.text_field :comment %>
                </p>
                <p>
                
                <%= form.hidden_field :user_id %>
                </p>
                
                <%= form.hidden_field :house_id %>
                </p>

                <p>
                <%= form.submit %>
                </p>
        <%end%> 
                </div>
                </div>
        
        
                

                

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFinalProject01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <style>
  img:hover {
    opacity: 0.5;
  }
  
  </style>
   
  
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@user.errors.count, "error") %> prohibited
    this user from being saved:
  </h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>



<%= form_for @user do |f| %>
  
    <label> Name:</label><br>
  <%= f.text_field :name %></br>

  <label>email:</label><br>
  <%= f.email_field:email %></br>

  <label> password:</label><br>
  <%= f.password_field :password %></br>

  <br>
  <%= f.submit %>
  </br>
<% end %>

app/views/users/edit.html.erb
<style>
img {
  opacity: 0.5;
}
</style>
<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
<div class="centered">

<h2>Edit User</h2>

<%= render partial: 'form', locals:{user: @user, button_label: "Update user"} %>
</div>

app/views/users/new.html.erb
<style>
img {
  opacity: 0.5;
}
</style>
<body>
<div class="container">
<%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
</body>
 <script>
 alert('Welcome! Please create a new account or log in');
</script>
<div class="centered">
<%= render partial: 'form', locals:{user: @user, button_label: "Create User"} %>
<br></br>
<button>
<%= link_to 'Log In', signin_path %>
</button>
</div>

app/views/users/show.html.erb
        <style>
        img {
        opacity: 0.5;
        }
        </style>
        <body>
        <div class="container">
        <%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
        </body>
        <div class="centered">
        <h1> Welcome <%= @user.name %></br> </h1>
        <h3></h3>
        <h3><%= @user.email %></br></h3> 
        <ul>
        <li><a href="#home">Open houses app</a></li>
        <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
        <div class="dropdown-content">
            <a  <%= link_to 'new House ', new_house_path %></a>
            <a  <%= link_to 'index House ', houses_path %></a>
            <a <%= link_to 'sign Out', signout_path %></a>
        </div>
        </div> 
        </li>
        </ul>




        
        <! -- link_to new_guest_path -->
        <! -- link_to /logout -->


        

app/views/welcome/home.html.erb
<style>
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial;
}

.header {
  text-align: center;
  padding: 32px;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
}

.column img {
  margin-top: 12px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
<body>

<!-- Header -->
<div class="header">
<% if current_user %>

<ul>
 <li><a href="#home">Logged in as <%= current_user.email %></a></li>
 <li class="dropdown">
   <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
   <div class="dropdown-content">
   <%= link_to 'Sign Out', signout_path %>
     <a <%= link_to 'Log In', signin_path %></a>
   </div>
 </li>
</ul>

<% else %>


<ul>
 <li><a href="#home">Home</a></li>
 <li class="dropdown">
   <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
   <div class="dropdown-content">
     <a <%= link_to 'Log In', signin_path %></a>
     <a <%= link_to 'Sign Up', new_user_path %></a>
     <a <%= link_to ' GitHub ', '/auth/github'%>.</a>
   </div>
 </li>
</ul>
<% end %>
</div>

<!-- Photo Grid -->
<div class="row"> 
  <div class="column">
  <%= image_tag("home-real-estate-106399.jpg",style:"width:100%")%>
  <%= image_tag("house-409451_1920.jpg" ,style:"width:100%")%>
  <%= image_tag("architecture-1477041_1280.jpg" ,style:"width:100%")%>
  
  </div>
  <div class="column">
  <%= image_tag("house-1407562_1920.jpg" ,style:"width:100%")%>
  <%= image_tag("living-room-3539587_1920.jpg" ,style:"width:100%")%>
  <%= image_tag("sale-3701777_1920.jpg" ,style:"width:100%")%>
  </div>